### ISSUE TITLE
Translation issue: "offensive" != "offensiv"

### ISSUE THREAD

**Issue by vasyugan** [wechange-eg/cosinnus-devops#15]
The German interface, next to an icon with an exclamation point in a triangle says "offensiven Inhalt melden". I guess the original goes something like "report offensive content". However, "offensive" and "offensiv" are false friends. "offensiv" in German  does not mean that you offend, but that you are aggressive about something, that you go on the offensive, typically with a positive connotation. 
Therefore, the correct translation would be "beleidigenden Inhalt melden".

**Comment by saschasommer** [comment]
Thanks for the report! We will fix the error soon!

**Comment by saschasommer** [comment]
Issue is fixed on live.
