### ISSUE TITLE
directreply seems to be broken

### ISSUE THREAD

**Issue by robwa** [wechange-eg/cosinnus-devops#16]
Beim Antworten auf persönliche Nachrichten bekomme ich den Hinweis, dass ich per Antwort-Funktion darauf antworten kann.

Im Empfänger erscheint dann aber nur die Adresse directreply@ ohne den Code. Die Antwort kommt auch nicht an.

**Comment by saschasommer** [comment]
Dass im Empfänger-Feld nur "directreply@" ohne Code erscheint ist richtig so. Benutzt wird nur der Code der im zitierten Antwort-bodytext der Email enthalten ist. Damit der Code im Text der Email erscheint, ist es deswegen wichtig, einfach nur auf die Email mit der Standard-antwort-funktion zu antworten. Aus Sicherheitsgründen kann auch nur von exakt der Email-Adresse geantwortet werden, an die die Mail auch verschickt wurde. 

@robwa Kann es denn daran gelegen haben? Oder funktioniert es auch nicht, wenn du es wie oben beschrieben versuchst? Von welchem email-programm hast du die email denn geschrieben? Und handelt es sich um wechange.de?

Die directreply Funktion funktioniert so für mich auf jeden Fall aktuell.

**Comment by robwa** [comment]
> Und handelt es sich um wechange.de?

Ja.

Ich verstehe: Ich darf den *Zitattext* also nicht verändern?

Das ist für mich aus der Erklärung nicht ersichtlich. Warum realisiert ihr das so und setzt den Code nicht in den Empfänger (bspw. via `Reply-To`-Header)?

Ich würde dann meinen Bug-Report in einen Feature-Request umwandeln. :)

Den Zitattext meines E-Mail-Programms verwende ich oft, um E-Mails "zwischen den Zeilen" zu beantworten.

Außerdem gibt es die Gefahr, dass ich eine Benachrichtigung weiterleite und dann jemand mit dem Code und gefälschter Absenderadresse in meinem Namen kommuniziert.

**Comment by saschasommer** [comment]
Verändern kann man den Zittattext. Das einzige was darin irgendwie enthalten sein muss ist dieser Teil:

`DIRECT-REPLY CODE: 
directreply+3+oenGDmGfhwOXlBxZiaQkXmWVKey53aTj@wechange.de `

Wir haben es so implementiert, weil es bei einigen unserer Portale Einschränkungen für Wildcard-Empfänger-Adressen gab, und wir so die Adresse fest auf directreply@ belassen konnten. 

Wir werden demnächst den Hilfestellungstext unten in den Mails verbessern und den Code anpassen (damit er nicht mehr wie eine Email aussieht), damit es etwas klarer wird. Ein kompletter Umbau des Features ist zur Zeit leider zu aufwändig.

**Comment by robwa** [comment]
Danke für die Hinweise.

> Ein kompletter Umbau des Features ist zur Zeit leider zu aufwändig.

Ich habe noch nicht in den relevanten Code geschaut. Aber wenn ich es richtig verstehe, lässt die an einigen Stellen verwendete Mail-Infrastruktur auch keinen Umbau zu.

Meine Fragen sind damit geklärt. Macht das Ticket gerne zu, wenn es für euch passend erscheint (vor oder nach Einbau der Verbesserungen).

**Comment by saschasommer** [comment]
Alles klar, gerne.

Ich mache das Ticket dann mal zu. Die Verbesserungen werden voraussichtlich im Januar kommen.
