### ISSUE TITLE
Determine Project-URL manually

### ISSUE THREAD

**Issue by wellemut** [wechange-eg/cosinnus-devops#18]
Our URL is much too long. 
https://wechange.de/project/ideen3-ev-raume-fur-entwicklung/
Would be nice if I could reduce it to https://wechange.de/project/ideen3

**Comment by fenglisch** [comment]
A workaround: Rename the project to just "Ideen3". The URL will change to your desired short version and a redirection will be created automatically. Then, you can rename it back to the long version and a redirection from the short URL to the long one will be created.
