### ISSUE TITLE
Iframe Code-Generator

### ISSUE THREAD

**Issue by wellemut** [wechange-eg/cosinnus-devops#19]
Simon L just helped me out manually to place our members-map on our page: http://ideenhochdrei.org/de/

It would be great if there is an widget-code generator for

- Map (members, projects and/or events)
- Calendar
- Newsfeed

And it would be nice to have a list of events underneath the map!

**Comment by fenglisch** [comment]
It's not a code generator, but at least a tutorial on how to get a custum iframe with your members: https://wechange.de/cms/2021/02/15/karte-einbetten-wechange-meets-wordpress/
Tutorials on how to transfer events and news from WECHANGE to the website will follow.
