### ISSUE TITLE
No Zoom in Iframe

### ISSUE THREAD

**Issue by wellemut** [wechange-eg/cosinnus-devops#21]
Is there an opton to modify zoom in the iframe (This map could be bigger: http://ideenhochdrei.org/de/verein/kennenlernen/menschen/)

**Comment by fenglisch** [comment]
Yes, there is! I wrote a tutorial about it: https://wechange.de/cms/2021/02/15/karte-einbetten-wechange-meets-wordpress/
(To close, @saschan )
