### ISSUE TITLE
Better Pads on Wechange!

### ISSUE THREAD

**Issue by wellemut** [wechange-eg/cosinnus-devops#23]
Having all Pads on one space is one of the best features at Wechange!

But as they have no headlines and no immages, we often use Pads from fairkom. Would be so nice if we could have all these fuctions too like on this board https://board.net/p/changeITcamp

- [x] Hedlines in different formats
- [ ] Embedding Pictures in the text
- [x] Comment-Function (addiotional to chat-function) so you can comment directly to text passages.

@simonline said, its just adding some more libraries. Roaldn Alton from fairkom said, he has figured out a good working stack of pad-addons which work very stable. I can ask him about details if needed.

**Comment by almereyda** [comment]
We also know of @codimd which generally makes a good Etherpad replacement.

There is also CryptPad.fr, if you like a more sophisticated writing environment.

**Comment by Ricks-ha** [comment]
If you already know a bunch about it why don't you implement it and make a PR?
Cause that really sounds great.

**Comment by fenglisch** [comment]
The pads have improved a lot since then. Headings, comments and other features are supported now (to close, @saschan )
