### ISSUE TITLE
owncloud for desktop-syn of wechage-documents

### ISSUE THREAD

**Issue by wellemut** [wechange-eg/cosinnus-devops#24]
When it comes to the Platform-decision in teams, it's often less the functionality that counts but much more the simplyness to use it. The big advantage in wechage is this feature, that once you have added all your team to the project, news, events, pads and files are on one place.

But files are not synced locally, one of the most important features for 90% of the teams. Especially for contact-Lists, Documents you are working on and files you often need to send by mail its annoying if you have to download and upload them all the time. In the end you forgot to upload them and your colleque is unable to work on it further... That made us by an owncloud for the "important" things and use wechange as a social-community.

Nextcloud would be a great solution! Each Project is one folder (max. 250 MB for free then it costs i.e. 5 GB for 1€ Prices like here: https://ocloud.de/product/nextcloud.html)
If you are part of the group and the project, then the project is a subfolder of the group-folder.  Otherwise all your wechange-Projects are just single folders (with subfolders) in your wechange-owncloud system)

You could syn also the owncloud.-calender with wechange and your mobile. And all wechage contacts could be synced too but thats for later.

**Comment by entfrickler** [comment]
If I could, I would vote for this feature!

**Comment by fenglisch** [comment]
Nextcloud is now fully implemented 🙂
To close, @saschan
