### ISSUE TITLE
Gruppen und Projekte in gleiches Dropdown

### ISSUE THREAD

**Issue by wellemut** [wechange-eg/cosinnus-devops#27]
Keiner versteht, ob man nun nach Gruppen oder Projekten suchen muss, weil man immer vergisst, was was ist.
Besser einfach in einer Liste darstellen. Die Gruppen erscheinen zuerst und jeweils die zughörigen Projekte in alphabetischer Riehenfolge darunter.

**Comment by fenglisch** [comment]
Danke für deinen Beitrag! Die Darstellung ist inzwischen so wie von dir vorgeschlagen. Das Issue kann geschlossen werden ( @saschan )
