### ISSUE TITLE
Euer Discord Invite Link in der Organisations-Beschreibung ist abgelaufen

### ISSUE THREAD

**Issue by roschaefer** [wechange-eg/cosinnus-devops#29]
Der Link von dieser Seite hier: https://github.com/wechange-eg

![20181213-211100](https://user-images.githubusercontent.com/2110676/49964905-f9814a80-ff1b-11e8-9abe-a031a7ba44d9.png)

**Comment by saschasommer** [comment]
@roschaefer Danke für den Hinweis! Habe einen dauerhaft gültigen Link eingefügt https://discord.gg/pX2TJMM
