### ISSUE TITLE
Setup docker for deployment

### ISSUE THREAD

**Issue by simonline** [wechange-eg/cosinnus-devops#4]
- [ ] Configure frontend proxy including letsencrypt (and networking)
- [ ] Remove unnecessary code volumes
- [ ] Add data and upload volumes
- [ ] Setup docker environment (e.g. libre.sh)
- [ ] Setup gunicorn web server

**Comment by simonline** [comment]
We're dokku compatible now. Next steps have been added to the issue description.

**Comment by almereyda** [comment]
I have added a checkbox about setting up gunicorn above.

**Comment by almereyda** [comment]
👏🏽
