### ISSUE TITLE
ModuleNotFoundError: No module named 'django_select2'

### ISSUE THREAD

**Issue by olsn** [wechange-eg/cosinnus-devops#42]
Hi,

i've setup the project with the simple steps of initializing the submodules.
And when running `docker-compose up` the web-container shows and error with

`ModuleNotFoundError: No module named 'django_select2'`

I was wondering if I am missing any steps? Of course the frontend is not available in the case.
Everything else runs fine as it seems.

**Comment by olsn** [comment]
Okay I managed to get past that error.
I had to manually install the python dependencies, this step seems it was  not covered by the provided steps in the readme.md
`pip3 install -r ./requirements_staging.txt`

**Comment by saschasommer** [comment]
Hmm, that's odd. This should have been covered by the step `pip install -r ./cosinnus-devops/requirements_local.txt` described in section https://github.com/wechange-eg/cosinnus-devops#set-up-the-local-wechange-source-and-install-all-dependencies. Did you maybe forget that step, or did it not work?

**Comment by olsn** [comment]
I chose "Option A" 😅 - without that "manual" install it did not work and afterwards it did work.
But I did not investigate any further - I might run it again to check.
