### ISSUE TITLE
GDAL is missing

### ISSUE THREAD

**Issue by olsn** [wechange-eg/cosinnus-devops#43]
I get following error in the web-docker-container when i use `docker-compose up`:

`django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.`

GDAL is installed though.
I'm using a clean Ubuntu 20.04 VM.

Can anyone help me with this?

**Comment by olsn** [comment]
Fixed it by adjusting the Dockerfile
```
RUN apt-get update && \
    apt-get install -y binutils libproj-dev gdal-bin
```

**Comment by saschasommer** [comment]
@olsn Thank you for reporting back on the fix! I included it in the dockerfile.
