### ISSUE TITLE
Feature: Assign task to multiple users

### ISSUE THREAD

**Issue by ALutz273** [wechange-eg/cosinnus-devops#44]
Hello Dev-Team,

It is not possible to assign a task to multiple users. 

But this feature would be very useful for us. 
Until now we use the "follow and comment" function.
Is it possible to implement this function?

**Comment by saschasommer** [comment]
Hello @ALutz273!

That does sound like a very useful feature! Unfortunately, the WECHANGE devs are currently extremely busy and thus we can sadly not implement any additional feature requests.

If you or someone you know has any coding experience however, you're more than welcome to submit a pull request with the feature!

Sorry again, and best regards,
Sascha from the WECHANGE Dev-Team
