### ISSUE TITLE
volltextsuche unbenutzbar

### ISSUE THREAD

**Issue by devZer0** [wechange-eg/cosinnus-devops#45]
moin, 

wechange wurde mir als teilnehmer eines grossen projekts mehrfach als leistungsfähige und angeblich konkurrenzlose opensource community & dokumenten plattform angepriesen. ich nutze es also, weil das für das projekt "gesetzt" ist. und ich habe jetzt wirklich eine ganze weile mit viel wohlwollen auf wechange geschaut.

meine erwartung von einer solchen plattform ist, daß ich dokumente die da eingestellt werden auch wiederfinden kann. 

leider wird diese erwartung nicht im ansatz erfüllt. nicht nur ich bin dort ständig auf der suche nach irgendwelchen dokumenten. ich habe mit anderen gesprochen und die sind da ähnlich gefrustet. die übersichtlichkeit ist da sicherlich verbesserungsfähig.

wäre an sich alles nicht so schlimm - gibt ja noch ne suchfunktion. 
nur - die volltextsuche im wechange funktioniert grösstenteils überhaupt nicht. sie bleibt überhaupt entweder hängen, liefert einem treffer die keine sind - oder liefert unmengen an treffern aus bereichen, in denen man garnicht suchen will. 

der support schrieb vor einer weile, daß das problem wegen mangelnder ressourcen auf absehbare zeit auch nicht lösbar ist.

im wechange nextcloud gibt es offensichtlich keine volltextsuche, auch wenn das technisch so wie ich das sehe durchaus möglich wäre.   

nun möchte man im projekt als "workaround" jetzt offenbar alle dokumente in die wechange nextcloud verschieben, weil da wenigstens filename-stringsuche funktioniert. 

wenn ich dazu mal was aus sicht eines ITler sagen darf (und sorry, wenn das jetzt sehr hart klingt, aber ich spreche halt gerne probleme offen , ehrlich und laut an) :

was will man im jahre 2020 mit einem online-tool was keine ordentliche volltext suchfunktion hat ?

**Comment by almereyda** [comment]
Danke für dieses Issue, das die Argumentation aus https://discourse.bits-und-baeume.org/t/alternative-loesungen-zu-wechange-gesucht/708/27 fortsetzt.

Ich denke hier kommen mehrere Faktoren zusammen. Für die Nextcloud-Integration empfiehlt es sich natürlich erstmal die https://apps.nextcloud.com/apps/fulltextsearch App zu benutzen und anhand von https://github.com/nextcloud/fulltextsearch/wiki mit Elasticsearch auszustatten. https://github.com/nextcloud/fulltextsearch_elasticsearch/wiki

Für Django gibt es sicherlich auch Adapter, welche automatisch Indizes über die Models erstellen könnten, um sie granular, d.h. mit Facets (nach Projekt, nach Organisation, etc.) durchsuchbar zu machen.

In der obigen Formulierung ist dieses Issue ein Epic, welches eher einer User Story gleicht.

Bekommen wir diese Darstellung in eine mit technischen Anforderungen für die Entwicklung umformuliert?

Wie können wir als professionelle Nutzerïnnen den Entwicklerïnnen dieser FLOSS unter die Arme greifen, um das erwünschte Feature herbeizuführen?

Ich denke abseits von technischen Erörterungen ist ein Issue Tracker kein gutes Umfeld, um Feature Requests und High-level Entwicklungen zu koordinieren. Gibt es auf Wechange eine Wechange Community, in der das diskutiert werden könnte?

**Comment by saschasommer** [comment]
@devZer0 die Volltextsuche ist jetzt für die Nextcloud aktiviert!
