### ISSUE TITLE
user auswählen leider unbenutzbar

### ISSUE THREAD

**Issue by devZer0** [wechange-eg/cosinnus-devops#46]
siehe screenshot

<img width="888" alt="grafik" src="https://user-images.githubusercontent.com/3506105/101266033-dd4fc700-374b-11eb-9d97-f641f43423d2.png">

**Comment by devZer0** [comment]
<img width="774" alt="grafik" src="https://user-images.githubusercontent.com/3506105/101266060-007a7680-374c-11eb-8d35-99eb16f74cc4.png">

**Comment by devZer0** [comment]
es gibt offensichtlich keine (!) möglichkeit "fabian" unter all den existierenden fabians zu finden.

**Comment by saschasommer** [comment]
@devZer0 ja, das ist aktuell extrem unübersichtlich. Wir sind dabei, eine bessere Lösung zu finden.

Eine Möglichkeit gibt es allerdings bis dahin: wenn du die *exakte* E-Mail-Adresse eines Benutzers kennst, kannst du sie dort eingeben, und damit findest du den exakten Benutzer-account.

**Comment by devZer0** [comment]
danke für den tip!
