### ISSUE TITLE
fast Täglichen Logout verhinden

### ISSUE THREAD

**Issue by wellemut** [wechange-eg/cosinnus-devops#49]
## Problem
Viele Nutzer (z.B. RolandCGN, @ludwig.schuster  und @helmut.wolman) klagen über regelmäßige rauswürfe bei RC. Das wieder einloggen geht in den meisten Fällen recht fix, ohne dass man die Zugangsdaten eingeben muss, aber trotzdem sehr nervig.
- Scheinbar wird man unbemerkt vom System abgemeldet, d.h. dann, wenn die App geschlossen ist. Ohne Fehlermeldung oder Hinweis. Erst wenn man die App dann mal wieder öffnet, kommt folgender Hinweis:
![2021-02-13T20_34_37.997Z](/uploads/928b832100d5674fe1c9f4442e5cc036/2021-02-13T20_34_37.997Z.jpeg)
![grafik](https://user-images.githubusercontent.com/15019030/110474097-8e655500-80df-11eb-87b8-43f5ba1f3ba5.png)

- Man bekommt dann auch keine Push-notifications mehr aufs handy, was natürlich doof ist, wenn man hinweise erwartet
- Es scheint immer im Zusammenhang mit Netzwerkwechseln des Endgerätes zu tun zu haben. Also wenn man am Handy vom WLAN ins mobile Netz kommt oder umgekehrt. Beim Laptop scheint es ähnlich zu sein.

### Mögliche Ursachen
RolandCGN hat beriets etwas Troubleshooting gemacht und hier dokumentiert im Kanal: #general / ständiges ausloggen in App 😡  https://rocketchat.wechange.de/channel/JH7DAGPxFiWd5Bk4F

- Roland denkt, es liegt daran, dass zu viele Login-Tokens neu erstellt werden (statt das die alten weiter verwendet werden) Durch ein Maximum von 50 Tokens, wird dann immer eines gelöscht, wenn durch ein netzwerkwechsel ein neues erstellt wird. Mehr dazu hier: https://rocketchat.wechange.de/channel/JH7DAGPxFiWd5Bk4F?msg=XTbov4euCosbmYFBq
  - Dort schlägt Roland einen Cronejob vor, der stündlich alte Tokes löscht: https://github.com/RocketChat/Rocket.Chat/pull/7812#issuecomment-780185937

## Lösung
??? @sascha.narr ist dran.

---
Internes Issue: https://git.sinnwerkstatt.com/wechange/wechange/-/issues/1348

**Comment by saschasommer** [comment]
This issue should be fixed as of April 8th.
